installer: replace variable kMaxFds with #define MAX_FDS
Previously, we declared kMaxFds as

  const int kMaxFds = 10;

and then used it as an array size in installer/util/evwaitkey.c:

  bool key_states[kMaxFds][KEY_MAX + 1] = {{}};

However, this is not actually a constant, leading to the compilation error:

  error: variable-sized object may not be initialized

This change instead uses #define MAX_FDS 10, which is a constant and
can be used as an array size.

BUG=chromium:1143437
TEST=bb add chromeos/toolchain/eve-llvm-tot-unstable

Change-Id: I7e4ed7ef1bee451d250a4c0840a4d1a335d4975d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2547112
Tested-by: Bob Haarman <inglorion@chromium.org>
Tested-by: Luis Lozano <llozano@chromium.org>
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Luis Lozano <llozano@chromium.org>
Reviewed-by: Amin Hassani <ahassani@chromium.org>