verity: fix gcc4.6 errors
Fixes the following errors:

verity-0.0.1-r33: verity_main.cc: In function 'int main(int, char**)':
verity-0.0.1-r33: verity_main.cc:54:15: error: variable 'root_hexdigest'
set but not used [-Werror=unused-but-set-variable]
verity-0.0.1-r33: cc1plus: all warnings being treated as errors
verity-0.0.1-r33:
verity-0.0.1-r33: make: ***
[/build/x86-generic/tmp/portage/chromeos-base/verity-0.0.1-r33/work/verity-0.0.1/build/verity_main.pie.o]
Error 1
verity-0.0.1-r33: make: *** Waiting for unfinished jobs....
verity-0.0.1-r33: verity_main.cc: In function 'int main(int, char**)':
verity-0.0.1-r33: verity_main.cc:54:15: error: variable 'root_hexdigest'
set but not used [-Werror=unused-but-set-variable]
verity-0.0.1-r33: cc1plus: all warnings being treated as errors
verity-0.0.1-r33:
verity-0.0.1-r33: make: ***
[/build/x86-generic/tmp/portage/chromeos-base/verity-0.0.1-r33/work/verity-0.0.1/build/verity_main.pic.o]
Error 1
verity-0.0.1-r33: emake failed
verity-0.0.1-r33:  * ERROR: chromeos-base/verity-0.0.1-r33 failed (compile
phase):
verity-0.0.1-r33:  *   failed to make verity
verity-0.0.1-r33:  *
verity-0.0.1-r33:  * Call stack:
verity-0.0.1-r33:  *     ebuild.sh, line  56:  Called src_compile
verity-0.0.1-r33:  *   environment, line 3053:  Called die
verity-0.0.1-r33:  * The specific snippet of code:
verity-0.0.1-r33:  *       emake OUT=${S}/build WITH_CHROME=$(use test &&
echo 1 || echo 0) SPLITDEBUG=$(use splitdebug && echo 1) verity ||
die "failed to make verity"

BUG=chromium-os:17883
TEST=compiled

Change-Id: Ibd2153d6b7b82814fb7bc959a01a20f910e5f83e
Reviewed-on: http://gerrit.chromium.org/gerrit/4405
Reviewed-by: Yasuhiro Matsuda <mazda@chromium.org>
Reviewed-by: Elly Jones <ellyjones@chromium.org>
Tested-by: Mandeep Singh Baines <msb@chromium.org>