Fix compiler errors when using libc++ in verity.
Rename macros min,max and to_bytes.
min and max macros are no longer allowed in c++.
to_bytes conflict with a header function in <locale>.

Fixes compilation errors:
/build/caroline/usr/include/c++/v1/locale:3596:48: error: too many arguments
verity-9999:       provided to function-like macro invocation
verity-9999:     byte_string to_bytes(const _Elem* __first, const _Elem* __last);
verity-9999: /mnt/host/source/src/platform/verity/include/linux/device-mapper.h:31:9: note:
verity-9999:       macro 'to_bytes' defined here
verity-9999: #define to_bytes(x) ((x) << SECTOR_SHIFT)

verity-9999: /build/caroline/usr/include/c++/v1/__undef_min_max:17:2: error: macro min is
verity-9999:       incompatible with C++. #undefing min [-Werror,-W#warnings]
verity-9999: #warning: macro min is incompatible with C++.  #undefing min
verity-9999: /build/caroline/usr/include/c++/v1/__undef_min_max:29:2: error: macro max is
verity-9999:       incompatible with C++. #undefing max [-Werror,-W#warnings]
verity-9999: #warning: macro max is incompatible with C++.  #undefing max

BUG=chromium:724628
TEST=verity compiles.

Change-Id: I709edbe48085c3dd692037957f9139010e9e5844
Reviewed-on: https://chromium-review.googlesource.com/547454
Commit-Ready: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Sonny Rao <sonnyrao@chromium.org>