Revert "typecd: Add MockPort for unit tests"
This reverts commit e0b2c8b538f238e9788d0d5a3f18f5edcdc5ad57.

Reason for revert:

failed on builder:

typecd-0.0.1-r112: ../../../../../../../tmp/portage/chromeos-base/typecd-0.0.1-r112/work/typecd-0.0.1/platform2/typecd/port_manager_test.cc:52:38: error: use of undeclared identifier 'TYPEC_MODE_DP'
typecd-0.0.1-r112:   EXPECT_CALL(*ec_util, EnterMode(0, TYPEC_MODE_DP))

https://ci.chromium.org/ui/p/chromeos/builders/postsubmit/volteer-snapshot/4857/overview


TYPEC_MODE_DP was renamed in
https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2631369
which landed in 13731.0.0

but
https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2632226
landed in 13732.0.0 but uses the old name which
should have failed in the CQ.

Exempt-From-Owner-Approval: broke CQ

Original change's description:
> typecd: Add MockPort for unit tests
>
> Add a MockPort class which derives from a regular Port class. With this,
> we can control the behaviour of the class (which modes it supports,
> whether cable discovery is complete, etc.) without having to set up an
> entire fake sysfs directory and really adding Cable and Partner objects.
> This in turn allows to test out various scenarios of the RunModeEntry()
> code.
>
> Make the relevant changes to the Port class to allow the MockPort to be
> defined.
>
> Also, add a simple unit test that uses a MockPort which can only enter
> DP, and validate that the ECUtil function is called correctly.
>
> BUG=b:168653671
> TEST=1. Check that all unit tests still pass.
>      2. Build and boot on a voxel. Validate that partner, cable and alt
>      mode hotplug removal events are being generated as expected in
>      typecd.log
>
> Change-Id: I1196144582ed2ee81b9c6fed0db0c1cf7ead02f0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2632226
> Reviewed-by: Mengqi Guo <mqg@chromium.org>
> Tested-by: Prashant Malani <pmalani@chromium.org>
> Commit-Queue: Prashant Malani <pmalani@chromium.org>

Bug: b:168653671
Change-Id: Ia88646423b555e8960073724317a221a12a3c21c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform2/+/2634622
Tested-by: caveh jalali <caveh@chromium.org>
Reviewed-by: caveh jalali <caveh@chromium.org>
Commit-Queue: caveh jalali <caveh@chromium.org>